### ISSUE TITLE
Better With Mod

### ISSUE THREAD

**Issue by dragondj** [Davoleo/Immersivecraft-MK#3]
i see a craft bug in the better with mod and i posted in screenshot
![image](https://user-images.githubusercontent.com/10321893/39673040-5d60667a-5135-11e8-94ff-393e881eda7c.png) plank make whith saw but saw don't work whithout mechanical energy of windmill or watermill

**Comment by Davoleo** [comment]
https://github.com/BetterWithMods/BetterWithMods/issues/905

**Comment by Davoleo** [comment]
you can use slabs instead of sidings
Closing this issue
