### ISSUE TITLE
native hemp oil 

### ISSUE THREAD

**Issue by dragondj** [Davoleo/Immersivecraft-MK#4]
i can not make it becouse for make it i need vanila brick and i can't created it for this moment is a craft blocked becouse for i make brick i need hempstone brick but for hemstone brick i need native hemp oil and for make it i need brick in alchemical condenser 
![image](https://user-images.githubusercontent.com/10321893/39673106-708e26aa-5136-11e8-8215-b91f0be1b796.png)

**Comment by Davoleo** [comment]
needs reboot
